### PR TITLE
Part 4

### PR DESCRIPTION
**Pull request by FilipHerman**

### CODE REVIEW

**Comment by jquave** [comment]
Thanks Filip. I think this is just the Part 4 of the tutorial, correct? I've created this as a separate branch so people can more easily follow along and see the state of the code at the end of Part 3.

**Comment by FilipHerman** [comment]
Sorry, I'm really new to all this. Is there a way to get the full source code of the complete sample?

**Comment by jquave** [comment]
Yeah, just clone down the branch for Part 4.
git pull origin Part4

**Comment by jquave** [comment]
I realize it may be confusing for new Git users to checkout the branch, so heres a zip from Part 4:
https://s3.amazonaws.com/JamesonQuave/Swift-Tutorial-Code-Part-4.zip

**Pull request closed without merging**
